### ISSUE TITLE
Is there room for jobs fetching optimisation?

### ISSUE THREAD

**Issue by Tinyakov** [hangfire-postgres/Hangfire.PostgreSql#317]
Hi! 

Earlier, I asked about the issue of a high volume of transactions with multiple workers (#306). Later, I studied the Hangfire.PostgreSql code and discovered that each worker in an application process has its own fetching loop (PostgreSqlJobQueue.Dequeue method) with its own DB requests, even if they use the same Hangfire queues.

The problem I am facing is the high TPS generated by these workers. Although each fetch DB request is light, they collectively create a parasitic load in my environment, as I have many applications running with 10+ workers each.

The idea I would like to share and discuss is to combine all of the workers' fetch requests into one consumer queue and have only one DB request loop. Instead of having 10 simultaneous fetch requests from 10 workers, we would have only one request loop waiting for the job. When a job appears, it would be returned to one of the workers as a fetch request result, and a new loop iteration would start to fetch the remaining queues. This should reduce the TPS in low-load environments like mine.

However, on the other hand, I think that implementing such synchronization may not be a good idea in a high-jobs-loaded environment. If there are many short jobs, each fetch request tends to return a new job, even with multiple workers, and we don't want to introduce synchronisation and slow things down.

What do you think about this? Is there room for improvement, maybe with a new option?

**Comment by dmitry-vychikov** [comment]
In what scenario are you getting high load? 
When there `are some pending jobs` or no `pending jobs`?  If the latter, we might do a simpler fix by introducing a short delay if worker did not find a job during previous request (unless this is already done...)

Also, how many queues do you have?

**Comment by dmitry-vychikov** [comment]
> When a job appears, it would be returned to one of the workers as a fetch request result, and a new loop iteration would start to fetch the remaining queues.

I feel this is very difficult or almost impossible for current hangfire storage design. It works in such way because there is need in high level of confidence that:
- one worker is working on a single job
- Job is being worked on by one worker
- Job is not abandoned

This is not straightforward even if it looks simple.

Also, this has to work reliable in multiserver scenario. Current implementation does.

The one you proposing – might not.

**Comment by dmitry-vychikov** [comment]
> but 1 second in my environments.

Why do you need it to be that low? 

If I'm not mistaken, workers are smart enough to get new job immediately after they completed the previous one. In other words, as long as you have lots of jobs, server will be processing them non stop.

QueuePollInterval is needed when there are no jobs in the queue.

**Comment by azygis** [comment]
> If I'm not mistaken, workers are smart enough to get new job immediately after they completed the previous one.

Not entirely true. The job is picked up immediately if the job has been queued in the same process while there are idle workers. Busy worker still has to become idle to be aware of new jobs.

**Comment by azygis** [comment]
Oh, no, that's not exactly what I meant. There is also `AutoResetEvent` that's used for dequeueing. When the job gets enqueued, the event is set and an idle worker immediately picks that job for processing.

At the moment I can neither confirm nor deny your claim, would need to investigate the flow a bit more. It would make sense that the worker checks for new jobs after executing anything though, since IIRC it's `do {} while(...)` and the thread waits inside `do`.

**Comment by azygis** [comment]
I still suggest lowering the queue poll interval either to a default one (15s) or at least something closer to 1min. There's still a possibility for the worker to NOT be idle when queueing the jobs, and you're then stuck waiting for a dequeue query for up to 15min, which I believe isn't what you really want.

Closing this issue for now, since moving the dequeue mechanism outside of workers is a bit too monumental of a task. It's always okay to create a PoC and share it here, though, so if you have the time and will to try something - feel free to do so, and then reopen the issue.

Thank you for #318! It's live in [NuGet](https://www.nuget.org/packages/Hangfire.PostgreSql/1.20.1) now.

**Comment by azygis** [comment]
Ahhh yes, sorry, you're right. I always forget about the worker checking the queue again after it finishes working on current job. Disregard!
