### ISSUE TITLE
Dashboard not showing history graph

### ISSUE THREAD

**Issue by zpxp** [hangfire-postgres/Hangfire.PostgreSql#333]
The dashboard doesn't show any data in the History Graph section, even though there is plenty of jobs. Its just all squashed up to the right. If i switch the provider to the stack exchange redis provider the Realtime Graph works fine. 

![image](https://github.com/hangfire-postgres/Hangfire.PostgreSql/assets/53557348/110b346a-9c5b-4666-a2f3-5b943d3764d5)

![image](https://github.com/hangfire-postgres/Hangfire.PostgreSql/assets/53557348/26c14a0b-abfb-4c12-9e6a-a96eab92944e)

Using these versions 
```
  <TargetFramework>net7.0</TargetFramework>

    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.5" />
    <PackageReference Include="Hangfire.Core" Version="1.8.5" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.20.0" />
```

**Comment by azygis** [comment]
Can confirm something is fishy with history chart. Some jobs appeared in it, but then after some time, they were gone from the chart. Need to investigate.

**Comment by azygis** [comment]
Yeah, that is because of counters being aggregated quite aggressively by default. By default, the aggregation is set to happen every 5 minutes, meaning we no longer have the counter information when it comes to date and/or time.

I think the default aggregation mechanism should change - `PostgreSqlOptions.CountersAggregateInterval` now only sets _how often_ the aggregation should happen, and it aggregates _everything_. It should be changed to aggregate only the counters older than your interval (or add another interval; one for _how often_, the second for _how old_).

The spare time I have at my hands is pretty tight right now. Hope to fix it this year, at least.

**Comment by azygis** [comment]
Whoops, we had missed to read aggregated counters for hourly stats. Will publish soon.
