### ISSUE TITLE
Could not place a lock on the resource 'hangfire:lock:recurring-job:jobid': Lock timeout.

### ISSUE THREAD

**Issue by duynv7** [hangfire-postgres/Hangfire.PostgreSql#365]
When I use to RecurringJob.AddOrUpdate() in .Net Core it throws an exception: **Could not place a lock on the resource 'hangfire:lock:recurring-job:jobid': Lock timeout.**
How to fix this problem?

**Version:**
Hangfire.PostgreSql: 1.20.8
Hangfire: 1.8.12
Hangfire.Core: 1.8.12
NetCore: 6.0.28

![image](https://github.com/hangfire-postgres/Hangfire.PostgreSql/assets/29879676/1fd0d25c-6920-4b11-9a98-9a3e9bd6c9b3)

**Comment by azygis** [comment]
You could check to see if `hangfire.lock` table contains any rows while the app is _not_ running. If there is, clear the table.

That is the most usual cause - happens if the process is killed without allowing it to shut down properly (e.g. killing the process or stopping the debugger which does not wait for the process to finish).

**Comment by duynv7** [comment]
> You could check to see if `hangfire.lock` table contains any rows while the app is _not_ running. If there is, clear the table.
> 
> That is the most usual cause - happens if the process is killed without allowing it to shut down properly (e.g. killing the process or stopping the debugger which does not wait for the process to finish).

Thanks!
